// GENERATED by `make builtins` from v8src/src/compiler/js-call-reducer.cc.
// Do not edit by hand: lib/derive-builtins.ts holds the extraction, and
// `make test` fails when this file and the pinned V8 source disagree.
//
// One name per `case Builtin::k<Name>` in that file — every builtin TurboFan
// lowers to inline code. The list says one thing only: at these callees there
// is no call boundary at all. It is NOT a fast-versus-slow classifier —
// Array.prototype.sort is lowered and is still O(n log n) with a comparator
// call per comparison (BUGS TC-126).

export const BUILTINS: {
  version: string;
  revision: string;
  lowered: readonly string[];
  statics: readonly string[];
} = {
  // The V8 this list is a fact about. The list is version-specific, so every
  // claim made from it names this pin (BUGS TC-126).
  version: '15.3.0.0',
  revision: 'c635f0d160b6e988b5ea5a907511a2929beb5d5e',
  lowered: [
    'ArrayBufferIsView', 'ArrayConstructor', 'ArrayEvery', 'ArrayFilter', 'ArrayForEach',
    'ArrayIncludes', 'ArrayIndexOf', 'ArrayIsArray', 'ArrayIteratorPrototypeNext', 'ArrayMap',
    'ArrayPrototypeAt', 'ArrayPrototypeEntries', 'ArrayPrototypeFind', 'ArrayPrototypeFindIndex',
    'ArrayPrototypeKeys', 'ArrayPrototypePop', 'ArrayPrototypePush', 'ArrayPrototypeShift',
    'ArrayPrototypeSlice', 'ArrayPrototypeSort', 'ArrayPrototypeValues', 'ArrayReduce',
    'ArrayReduceRight', 'ArraySome', 'BigIntAsIntN', 'BigIntAsUintN', 'BigIntConstructor',
    'BooleanConstructor', 'DataViewPrototypeGetBigInt64', 'DataViewPrototypeGetBigUint64',
    'DataViewPrototypeGetByteLength', 'DataViewPrototypeGetByteOffset',
    'DataViewPrototypeGetFloat16', 'DataViewPrototypeGetFloat32', 'DataViewPrototypeGetFloat64',
    'DataViewPrototypeGetInt16', 'DataViewPrototypeGetInt32', 'DataViewPrototypeGetInt8',
    'DataViewPrototypeGetUint16', 'DataViewPrototypeGetUint32', 'DataViewPrototypeGetUint8',
    'DataViewPrototypeSetBigInt64', 'DataViewPrototypeSetBigUint64',
    'DataViewPrototypeSetFloat16', 'DataViewPrototypeSetFloat32', 'DataViewPrototypeSetFloat64',
    'DataViewPrototypeSetInt16', 'DataViewPrototypeSetInt32', 'DataViewPrototypeSetInt8',
    'DataViewPrototypeSetUint16', 'DataViewPrototypeSetUint32', 'DataViewPrototypeSetUint8',
    'DateNow', 'DatePrototypeGetDate', 'DatePrototypeGetDay', 'DatePrototypeGetFullYear',
    'DatePrototypeGetHours', 'DatePrototypeGetMinutes', 'DatePrototypeGetMonth',
    'DatePrototypeGetSeconds', 'DatePrototypeGetTime', 'FastFunctionPrototypeBind',
    'FunctionPrototypeApply', 'FunctionPrototypeCall', 'FunctionPrototypeHasInstance',
    'GeneratorPrototypeNext', 'GetContinuationPreservedEmbedderData', 'GlobalIsFinite',
    'GlobalIsNaN', 'MapIteratorPrototypeNext', 'MapPrototypeEntries', 'MapPrototypeGet',
    'MapPrototypeGetSize', 'MapPrototypeHas', 'MapPrototypeKeys', 'MapPrototypeValues', 'MathAbs',
    'MathAcos', 'MathAcosh', 'MathAsin', 'MathAsinh', 'MathAtan', 'MathAtan2', 'MathAtanh',
    'MathCbrt', 'MathCeil', 'MathClz32', 'MathCos', 'MathCosh', 'MathExp', 'MathExpm1',
    'MathFloor', 'MathFround', 'MathImul', 'MathLog', 'MathLog10', 'MathLog1p', 'MathLog2',
    'MathMax', 'MathMin', 'MathPow', 'MathRound', 'MathSign', 'MathSin', 'MathSinh', 'MathSqrt',
    'MathTan', 'MathTanh', 'MathTrunc', 'NumberConstructor', 'NumberIsFinite', 'NumberIsInteger',
    'NumberIsNaN', 'NumberIsSafeInteger', 'NumberParseInt', 'ObjectConstructor', 'ObjectCreate',
    'ObjectGetPrototypeOf', 'ObjectIs', 'ObjectPrototypeGetProto',
    'ObjectPrototypeHasOwnProperty', 'ObjectPrototypeIsPrototypeOf', 'PromiseConstructor',
    'PromisePrototypeCatch', 'PromisePrototypeFinally', 'PromisePrototypeThen',
    'PromiseResolveTrampoline', 'ReflectApply', 'ReflectConstruct', 'ReflectGet',
    'ReflectGetPrototypeOf', 'ReflectHas', 'RegExpPrototypeTest', 'ReturnReceiver',
    'SetContinuationPreservedEmbedderData', 'SetIteratorPrototypeNext', 'SetPrototypeEntries',
    'SetPrototypeGetSize', 'SetPrototypeHas', 'SetPrototypeValues', 'StringConstructor',
    'StringFromCharCode', 'StringFromCodePoint', 'StringIteratorPrototypeNext',
    'StringPrototypeCharAt', 'StringPrototypeCharCodeAt', 'StringPrototypeCodePointAt',
    'StringPrototypeConcat', 'StringPrototypeEndsWith', 'StringPrototypeIncludes',
    'StringPrototypeIndexOf', 'StringPrototypeIterator', 'StringPrototypeLocaleCompareIntl',
    'StringPrototypeSlice', 'StringPrototypeStartsWith', 'StringPrototypeSubstr',
    'StringPrototypeSubstring', 'StringPrototypeToLowerCaseIntl',
    'StringPrototypeToUpperCaseIntl', 'TypedArrayConstructor', 'TypedArrayPrototypeByteLength',
    'TypedArrayPrototypeByteOffset', 'TypedArrayPrototypeEntries', 'TypedArrayPrototypeKeys',
    'TypedArrayPrototypeLength', 'TypedArrayPrototypeToStringTag', 'TypedArrayPrototypeValues',
    'WeakMapPrototypeGet',
  ],
  // The lowered subset with a static JS spelling — the only form a textual
  // match can recognise. See staticForms() in lib/derive-builtins.ts.
  statics: [
    'Array.isArray', 'ArrayBuffer.isView', 'BigInt.asIntN', 'BigInt.asUintN', 'Date.now',
    'Math.abs', 'Math.acos', 'Math.acosh', 'Math.asin', 'Math.asinh', 'Math.atan', 'Math.atan2',
    'Math.atanh', 'Math.cbrt', 'Math.ceil', 'Math.clz32', 'Math.cos', 'Math.cosh', 'Math.exp',
    'Math.expm1', 'Math.floor', 'Math.fround', 'Math.imul', 'Math.log', 'Math.log10',
    'Math.log1p', 'Math.log2', 'Math.max', 'Math.min', 'Math.pow', 'Math.round', 'Math.sign',
    'Math.sin', 'Math.sinh', 'Math.sqrt', 'Math.tan', 'Math.tanh', 'Math.trunc',
    'Number.isFinite', 'Number.isInteger', 'Number.isNaN', 'Number.isSafeInteger',
    'Number.parseInt', 'Object.create', 'Object.is', 'Promise.resolve', 'Reflect.apply',
    'Reflect.construct', 'Reflect.get', 'Reflect.has', 'String.fromCharCode',
    'String.fromCodePoint',
  ],
};
