// GENERATED by `make numbers` from the .jl sweeps. Do not edit by hand:
// lib/derive.ts holds the query behind every string here, and `make test`
// fails when this file and the data disagree.

export const N: Record<string, string> = {
  // shapes-calibrated.jl: five shapes, reads only, L1 through RAM
  'elem.reads': '4.4-11.5x',
  // shapes-calibrated.jl: construction counted, L1 and L2, two to five shapes
  'elem.constr.l1l2': '1.28-3.91x',
  // shapes-calibrated.jl: construction counted at RAM size, two to five shapes
  'elem.constr.l3': '1.00-1.22x',
  // shapes-calibrated.jl: the whole sweep
  'elem.cells': '24',
  // shapes-calibrated.jl: two to four shapes, reads only, every size — where the rule stays quiet
  'elem.silent.24': '1.05-1.81x',
  // dispatch.jl: a method on a prototype, five and six shapes, reads only — the older sweep, not re-measured under r2
  'disp.proto.reads': '14.6-20.0x',
  // dispatch.jl: a method on a prototype, four shapes, reads only at L1 — the older sweep, not re-measured under r2
  'disp.proto.four': '1.56x',
  // dispatch.jl: a method on a prototype, five shapes, reads only at L1 — the older sweep, not re-measured under r2
  'disp.proto.five': '19.37x',
  // dispatch.jl: one shared function held as an own property, five and six shapes, reads only — the older sweep, not re-measured under r2
  'disp.shared.reads': '6.9-8.2x',
  // dispatch.jl: five shapes with construction counted, prototype and own-property, L1 and L2 — the older sweep, not re-measured under r2
  'disp.constr.l1l2': '1.9-5.5x',
  // dispatch.jl: a method on a prototype at RAM size, five and six shapes, the replicated cells — the older sweep, not re-measured under r2
  'disp.constr.l3.five': '1.46-1.94x',
  // dispatch.jl: the same cells at two to four shapes — the older sweep, not re-measured under r2
  'disp.constr.l3.four': '0.93-1.20x',
  // dispatch.jl: the whole sweep — the older sweep, not re-measured under r2
  'disp.cells': '80',
  // dispatch.jl: four shapes on a prototype method, reads only, every size — where the rule is quiet — the older sweep, not re-measured under r2
  'disp.silent.proto4': '1.38-1.56x',
  // dispatch.jl: four shapes on one shared own-property function, reads only, every size — the older sweep, not re-measured under r2
  'disp.silent.shared4': '2.14-2.21x',
  // dispatch.jl: every shape carrying its OWN function, reads only, two to six targets, every size — the older sweep, not re-measured under r2
  'disp.silent.own': '3.5-14.8x',
  // spread.jl: array spread against push at n=1000, construction counted, both sweeps
  'spread.array.n1000': '149-166x',
  // spread.jl: the same at n=10000, the three replications
  'spread.array.n10000': '1766-1889x',
  // spread.jl: the two sweeps of that cell that predate the replication — the older sweep, not re-measured under r2
  'spread.array.n10000.earlier': '1877x and 2348x',
  // spread.jl: acc.concat(v) against push at n=1000, construction counted
  'spread.concat': '777-807x',
  // spread.jl: every interval measured for that cell
  'spread.concat.ci': '695-928',
  // spread.jl: the finished array read back, spread against push, both sizes and both sweeps
  'spread.array.reads': '0.96-1.02x',
  // spread-object.jl: the finished object read back, spread against keyed assignment, n=500
  'spread.object.reads': '0.03x',
  // spread-object.jl: object spread against keyed assignment at n=500, the three replications
  'spread.object': '186-200x',
  // spread-object.jl: Object.assign({}, acc, …) at n=500, the three replications
  'spread.assign': '814-887x',
  // spread.jl + spread-object.jl: all four accumulating forms with construction excluded, every size
  'spread.silent.reads': '0.03-1.87x',
  // strings.jl: s = s + x, s += x and s = s.concat(x) against a push-and-join, building only
  'spread.silent.strings.build': '0.26-0.52x',
  // strings.jl: the same three with the read back counted
  'spread.silent.strings.incl': '0.78-1.13x',
  // strings.jl: every interval measured for those nine cells
  'spread.silent.strings.incl.ci': '0.71-1.48',
  // select.jl: the chosen value stored where it outlives the loop, both sizes
  'select.heap': '2.56-2.87x',
  // select.jl: the intervals at n=10000, across the first sweep and the three replications
  'select.heap.ci10k': '2.59-2.92',
  // select.jl: the intervals at n=100000, across the first sweep and the three replications
  'select.heap.ci100k': '2.30-3.09',
  // select.jl: the whole sweep
  'select.cells': '6',
  // select.jl: the same loop on numbers, both sizes — where the rule stays quiet
  'select.silent.number': '0.88-1.22x',
  // select.jl: every interval measured on numbers
  'select.silent.number.ci': '0.84-1.30',
  // select.jl: the boxed form kept in a local, where escape analysis could see it, both sizes
  'select.silent.local': '2.01-2.45x',
  // chained.jl: xs.map(f).filter(g) against one fused pass at n=1000, construction counted
  'chained.mapfilter': '6.48-7.51x',
  // chained.jl: every interval measured for that cell
  'chained.mapfilter.ci': '5.62-7.90',
  // chained.jl: Object.entries(o).map(f) against a for-in walk at n=1000, construction counted
  'chained.entries.n1000': '3.67-3.76x',
  // chained.jl: every interval measured for that cell
  'chained.entries.n1000.ci': '3.50-4.04',
  // chained.jl: the same at n=10000
  'chained.entries.n10000': '2.55-2.61x',
  // chained.jl: every interval measured for that cell
  'chained.entries.n10000.ci': '2.23-2.97',
  // chained.jl: the 0.3 sweep, which is every row the dispatch-table kernel wrote
  'chained.cells': '24',
  // chained.jl: reading the finished array back, all six chained forms, both sizes
  'chained.silent.reads': '0.95-1.10x',
  // chained.jl: map then filter with construction counted at n=100000, where bandwidth dominates
  'chained.silent.big': '1.44-1.52x',
  // chained.jl: Object.keys(o).map(f) against the for-in walk that fuses it, construction counted
  'chained.silent.keys': '0.84-1.00x',
  // chained.jl: xs.map(f).sort() against the same map, construction counted — .sort() is in place
  'chained.silent.sort': '0.99-1.09x',
  // chained.jl: every interval measured for those cells
  'chained.silent.sort.ci': '0.91-1.22',
  // chained.jl: s.split(sep).map(f).join(sep) against two different fusions, construction counted
  'chained.silent.split': '0.99-1.10x',
  // inline.jl: a callee past the inlining budget against the same callee under it
  'inline.reads': '3.21-4.95x',
  // inline.jl: the interval at n=100000
  'inline.ci100k': '2.54-5.58',
  // inline.jl: the interval at n=1000
  'inline.ci1000': '4.34-5.22',
  // inline.jl: the whole sweep
  'inline.cells': '2',
  // delete.jl: one delete per object, reads only, at n=16384 and n=262144
  'delete.rows': '12.3-23.0x',
  // delete.jl: the same delete against assigning undefined instead, n=16384
  'delete.vs.undefined': '11.5-13.2x',
  // delete.jl: one object with one delete, reads only, every size and every sweep
  'delete.single': '13.1-15.1x',
  // delete.jl: one delete per object with construction counted, n=256
  'delete.rows.constr': '23.7-24.8x',
  // delete.jl: the single object with construction counted, every size
  'delete.single.constr': '3.3-8.7x',
  // delete.jl: the whole sweep
  'delete.cells': '16',
  // delete.jl: assigning undefined instead of deleting, reads only — the fix, not the defect
  'delete.silent.undef.reads': '1.00-1.06x',
  // delete.jl: every interval measured for that cell
  'delete.silent.undef.reads.ci': '0.96-1.12',
  // delete.jl: the same, with construction counted
  'delete.silent.undef.build': '0.98-1.18x',
  // example.jl: remeda mergeAll — the caller's reads on the result, both sizes, all six sweeps
  'ex.mergeall.reads': '0.11-0.12x',
};
