// GENERATED by `make numbers` from the .jl sweeps. Do not edit by hand:
// lib/derive.ts holds the query behind every string here, and `make test`
// fails when this file and the data disagree.

export const N: Record<string, string> = {
  // shapes-calibrated.jl: five shapes, reads only, L1 through RAM
  'elem.reads': '3.6-10.6x',
  // shapes-calibrated.jl: construction counted, L1 and L2, two to five shapes
  'elem.constr.l1l2': '1.25-3.52x',
  // shapes-calibrated.jl: construction counted at RAM size, the four replicated cells only
  'elem.constr.l3': '1.05-1.20x',
  // shapes-calibrated.jl: the whole sweep
  'elem.cells': '24',
  // dispatch.jl: a method on a prototype, five and six shapes, reads only
  'disp.proto.reads': '14.6-20.0x',
  // dispatch.jl: a method on a prototype, four shapes, reads only at L1
  'disp.proto.four': '1.56x',
  // dispatch.jl: a method on a prototype, five shapes, reads only at L1
  'disp.proto.five': '19.37x',
  // dispatch.jl: one shared function held as an own property, five and six shapes, reads only
  'disp.shared.reads': '6.9-8.2x',
  // dispatch.jl: five shapes with construction counted, prototype and own-property, L1 and L2
  'disp.constr.l1l2': '1.9-5.5x',
  // dispatch.jl: a method on a prototype at RAM size, five and six shapes, the replicated cells
  'disp.constr.l3.five': '1.46-1.94x',
  // dispatch.jl: the same cells at two to four shapes
  'disp.constr.l3.four': '0.93-1.20x',
  // dispatch.jl: the whole sweep
  'disp.cells': '80',
  // spread.jl: array spread against push at n=1000, construction counted, both sweeps
  'spread.array.n1000': '156-177x',
  // spread.jl: the same at n=10000, the three replications
  'spread.array.n10000': '1750-2011x',
  // spread.jl: the two sweeps of that cell that predate the replication
  'spread.array.n10000.earlier': '1877x and 2348x',
  // spread.jl: acc.concat(v) against push at n=1000, construction counted
  'spread.concat': '779x',
  // spread.jl: the interval of that cell
  'spread.concat.ci': '733-821',
  // spread.jl: the finished array read back, spread against push, both sizes and both sweeps
  'spread.array.reads': '0.96-1.07x',
  // spread-object.jl: the finished object read back, spread against keyed assignment, n=500
  'spread.object.reads': '0.02-0.03x',
  // spread-object.jl: object spread against keyed assignment at n=500, the three replications
  'spread.object': '188-203x',
  // spread-object.jl: Object.assign({}, acc, …) at n=500, the three replications
  'spread.assign': '846-875x',
  // select.jl: the chosen value stored where it outlives the loop, both sizes
  'select.heap': '2.65-2.73x',
  // select.jl: the interval at n=10000
  'select.heap.ci10k': '2.48-2.81',
  // select.jl: the interval at n=100000
  'select.heap.ci100k': '2.58-2.88',
  // select.jl: the whole sweep
  'select.cells': '6',
  // chained.jl: xs.map(f).filter(g) against one fused pass at n=1000, construction counted
  'chained.mapfilter': '7.89x',
  // chained.jl: the interval of that cell
  'chained.mapfilter.ci': '7.41-8.41',
  // chained.jl: Object.entries(o).map(f) against a for-in walk at n=1000, construction counted
  'chained.entries.n1000': '3.59x',
  // chained.jl: the interval of that cell
  'chained.entries.n1000.ci': '3.44-3.77',
  // chained.jl: the same at n=10000
  'chained.entries.n10000': '2.65x',
  // chained.jl: the interval of that cell
  'chained.entries.n10000.ci': '2.56-2.74',
  // chained.jl: the 0.3 sweep, which is every row the dispatch-table kernel wrote
  'chained.cells': '24',
  // inline.jl: a callee past the inlining budget against the same callee under it
  'inline.reads': '4.42-4.79x',
  // inline.jl: the interval at n=100000
  'inline.ci100k': '4.18-4.70',
  // inline.jl: the interval at n=1000
  'inline.ci1000': '4.56-5.05',
  // inline.jl: the whole sweep
  'inline.cells': '2',
  // delete.jl: one delete per object, reads only, at n=16384 and n=262144
  'delete.rows': '12.6-17.1x',
  // delete.jl: the same delete against assigning undefined instead, n=16384
  'delete.vs.undefined': '12.4-12.9x',
  // delete.jl: one object with one delete, reads only, every size and every sweep
  'delete.single': '13.3-15.6x',
  // delete.jl: one delete per object with construction counted, n=256
  'delete.rows.constr': '23.2-24.3x',
  // delete.jl: the single object with construction counted, every size
  'delete.single.constr': '3.2-7.0x',
  // delete.jl: the whole sweep
  'delete.cells': '16',
  // example.jl: remeda mergeAll — the caller's reads on the result, both sizes, all six sweeps
  'ex.mergeall.reads': '0.11-0.12x',
};
